### ISSUE TITLE
Feature Request: Use Publish Profile file in repo instead of in secrets

### ISSUE THREAD

**Issue by philip-gai** [Azure/webapps-deploy#199]
I would like to use version control for my publish profile instead of just having it in secrets.

My ideal setup would be:
1. Download the publish profile from Azure portal
2. Replace any passwords with tokens aka `#{USER_PWD}#`
2. Add it to the repo
4. Use <https://github.com/cschleiden/replace-tokens> to replace the tokens in a step in the workflow
5. Deploy using the local file relative path instead of a secret aka `publish-profile: 'deploy/repost.PublishSettings'`

Here is an example workflow file I tested it with: <https://github.com/philip-gai/repost/actions/runs/1344501354/workflow>

**Comment by JasonFreeberg** [comment]
Thank you but this request is declined due to other priorities. 

Plus, I don't think it's a good practice to have that information in source control where a less sophisticated user could make the easy mistake of forgetting to remove the secrets as they put the publish profile into their repository.
