### ISSUE TITLE
Deploy react in Azure app service Window (Publish: Code) With Private endpoint

### ISSUE THREAD

**Issue by anjoantoque** [Azure/webapps-deploy#244]
Hi,

Can you help me to figure out on how to deploy my package in azure app with private endpoints? My action is always failing, below is the error I am getting. Thanks

```
Run azure/webapps-deploy@v2
Package deployment using ZIP Deploy initiated.
Error: Failed to deploy web package to App Service.
Error: Deployment Failed with Error: Error: Failed to deploy web package to App Service.
Ip Forbidden (CODE: 403)
```

**Comment by shpraka** [comment]
@anjoantoque Without additional changes, internet-based CI systems like GitHub and Azure DevOps may not work for private endpoint because the publishing endpoint isn't internet accessible. 

To resolve your issue, in Azure create a VM or a VM Scale Set either in the same VNet as your private endpoint of the web app. Then [add this scale set as a new agent pool](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops#create-the-scale-set-agent-pool). Finally make sure that in the release pipeline settings, the release is using this new agent pool.

Few other resources for Private Endpoint, Self-hosted ADO Agents and Github Runners are https://learn.microsoft.com/en-us/azure/app-service/networking/private-endpoint, https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser and https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners.

**Comment by shpraka** [comment]
@anjoantoque let us know if the above steps helped.

**Comment by shpraka** [comment]
Closing because of no response from customer. Feel free to create new one incase of any issues.
